/**
 * DYNAMIC PATROL PLANNING - Core Tactical Datasets
 * Realistic law enforcement & emergency response demo data
 */

const SECTORS_DATA = [
  {
    id: "SEC-01",
    code: "Alpha",
    name: "Downtown Financial Core",
    description: "High-density commercial towers, banking headquarters, transit corridors, and heavy pedestrian foot traffic during business hours.",
    center: [41.8818, -87.6324],
    polygon: [
      [41.8870, -87.6380],
      [41.8870, -87.6260],
      [41.8760, -87.6260],
      [41.8760, -87.6380]
    ],
    baseRisk: 68,
    activeUnits: 3,
    populationDensity: "High (Commercial)",
    targetPatrolFreqMins: 30,
    lastPatrolMinsAgo: 18,
    primaryCrimes: ["Larceny / Theft", "Fraud", "Traffic Gridlock", "Trespassing"]
  },
  {
    id: "SEC-02",
    code: "Bravo",
    name: "River North & Entertainment Strip",
    description: "Vibrant nightlife hub with 80+ bars, clubs, high-end dining, and riverwalk access. High rate of late-night alcohol-related incidents.",
    center: [41.8925, -87.6335],
    polygon: [
      [41.8985, -87.6390],
      [41.8985, -87.6270],
      [41.8870, -87.6260],
      [41.8870, -87.6380]
    ],
    baseRisk: 86,
    activeUnits: 2,
    populationDensity: "Very High (Nightlife)",
    targetPatrolFreqMins: 20,
    lastPatrolMinsAgo: 38,
    primaryCrimes: ["Assault", "DUI", "Disorderly Conduct", "Armed Robbery"]
  },
  {
    id: "SEC-03",
    code: "Charlie",
    name: "West Loop & Fulton Market",
    description: "Former meatpacking converted to tech corporate offices, culinary hotspot, and rapid condo development. Cargo vehicle theft & burglaries.",
    center: [41.8845, -87.6480],
    polygon: [
      [41.8900, -87.6580],
      [41.8900, -87.6380],
      [41.8780, -87.6380],
      [41.8780, -87.6580]
    ],
    baseRisk: 58,
    activeUnits: 2,
    populationDensity: "Moderate-High",
    targetPatrolFreqMins: 45,
    lastPatrolMinsAgo: 52,
    primaryCrimes: ["Motor Vehicle Theft", "Commercial Burglary", "Package Theft"]
  },
  {
    id: "SEC-04",
    code: "Delta",
    name: "South Transit & Waterfront Concourse",
    description: "Intermodal rail hub, subway terminals, bus concourses, and parks. Known pickpocketing corridor and pedestrian traffic conflicts.",
    center: [41.8710, -87.6280],
    polygon: [
      [41.8760, -87.6380],
      [41.8760, -87.6200],
      [41.8640, -87.6200],
      [41.8640, -87.6380]
    ],
    baseRisk: 74,
    activeUnits: 1,
    populationDensity: "High (Transit)",
    targetPatrolFreqMins: 25,
    lastPatrolMinsAgo: 95, // BLIND SPOT ALERT
    primaryCrimes: ["Pickpocketing / Larceny", "Narcotics", "Vagrancy / Trespass", "Pedestrian Collision"]
  },
  {
    id: "SEC-05",
    code: "Echo",
    name: "Magnificent Mile & Streeterville",
    description: "Premier luxury shopping avenue, major hospital medical district, and lakeside hotels. High-value retail smash-and-grab targets.",
    center: [41.8940, -87.6220],
    polygon: [
      [41.9010, -87.6270],
      [41.9010, -87.6150],
      [41.8870, -87.6150],
      [41.8870, -87.6260]
    ],
    baseRisk: 62,
    activeUnits: 2,
    populationDensity: "High (Retail / Medical)",
    targetPatrolFreqMins: 35,
    lastPatrolMinsAgo: 24,
    primaryCrimes: ["Organized Retail Theft", "Shoplifting", "Hit and Run", "Harassment"]
  },
  {
    id: "SEC-06",
    code: "Foxtrot",
    name: "Near North Arts & Residential Grid",
    description: "Brownstone residences, gallery district, historic schools and boutiques. Moderate property crime, package theft, and bicycle collisions.",
    center: [41.9020, -87.6340],
    polygon: [
      [41.9080, -87.6440],
      [41.9080, -87.6270],
      [41.8985, -87.6270],
      [41.8985, -87.6440]
    ],
    baseRisk: 42,
    activeUnits: 1,
    populationDensity: "Moderate (Residential)",
    targetPatrolFreqMins: 60,
    lastPatrolMinsAgo: 40,
    primaryCrimes: ["Residential Burglary", "Vandalism", "Bike / Pedestrian Accidents"]
  }
];

const ACCIDENT_HOTSPOTS = [
  {
    id: "ACC-01",
    intersection: "Michigan Ave & Wacker Dr",
    lat: 41.8885,
    lng: -87.6246,
    sectorId: "SEC-01",
    collisionCount30d: 28,
    severityIndex: 88,
    primaryCause: "Speeding / Failure to Yield",
    peakHours: "17:00 - 19:30",
    fatalAccidents: 1,
    pedestrianInvolved: true,
    riskFactor: "Multi-level double deck bridge intersection with heavy bus transit"
  },
  {
    id: "ACC-02",
    intersection: "Ontario St & Clark St",
    lat: 41.8932,
    lng: -87.6315,
    sectorId: "SEC-02",
    collisionCount30d: 22,
    severityIndex: 82,
    primaryCause: "DUI / Red Light Violation",
    peakHours: "23:00 - 02:30",
    fatalAccidents: 0,
    pedestrianInvolved: true,
    riskFactor: "Highway feeder ramp intersection with heavy nightclub pedestrian crossing"
  },
  {
    id: "ACC-03",
    intersection: "Halsted St & Randolph St",
    lat: 41.8845,
    lng: -87.6475,
    sectorId: "SEC-03",
    collisionCount30d: 19,
    severityIndex: 65,
    primaryCause: "Commercial Delivery Blocking / Blind Turns",
    peakHours: "11:30 - 14:00",
    fatalAccidents: 0,
    pedestrianInvolved: false,
    riskFactor: "Narrow restaurant row with double-parked supply trucks and valet congestion"
  },
  {
    id: "ACC-04",
    intersection: "State St & Congress Pkwy (Ida B. Wells)",
    lat: 41.8752,
    lng: -87.6278,
    sectorId: "SEC-04",
    collisionCount30d: 26,
    severityIndex: 85,
    primaryCause: "Aggressive Lane Merging / Speeding",
    peakHours: "07:30 - 09:30",
    fatalAccidents: 1,
    pedestrianInvolved: true,
    riskFactor: "Wide expressway entrance bottleneck merging across university student crosswalks"
  },
  {
    id: "ACC-05",
    intersection: "Michigan Ave & Chicago Ave",
    lat: 41.8970,
    lng: -87.6241,
    sectorId: "SEC-05",
    collisionCount30d: 21,
    severityIndex: 72,
    primaryCause: "Distracted Driving / Pedestrian Crossings",
    peakHours: "16:00 - 18:30",
    fatalAccidents: 0,
    pedestrianInvolved: true,
    riskFactor: "Massive tourist pedestrian volumes combined with emergency hospital ambulance corridor"
  },
  {
    id: "ACC-06",
    intersection: "Dearborn St & Adams St",
    lat: 41.8794,
    lng: -87.6295,
    sectorId: "SEC-01",
    collisionCount30d: 14,
    severityIndex: 58,
    primaryCause: "Bike Lane Conflict / Right Hook",
    peakHours: "08:00 - 09:30",
    fatalAccidents: 0,
    pedestrianInvolved: true,
    riskFactor: "Protected two-way cycle track crossing vehicle turning lane"
  },
  {
    id: "ACC-07",
    intersection: "Hubbard St & Wells St",
    lat: 41.8898,
    lng: -87.6341,
    sectorId: "SEC-02",
    collisionCount30d: 17,
    severityIndex: 78,
    primaryCause: "DUI / Late Night Speeding",
    peakHours: "01:00 - 03:30",
    fatalAccidents: 0,
    pedestrianInvolved: true,
    riskFactor: "Under-El rail pillars creating visual blind spots near tavern cluster"
  },
  {
    id: "ACC-08",
    intersection: "Roosevelt Rd & Michigan Ave",
    lat: 41.8675,
    lng: -87.6242,
    sectorId: "SEC-04",
    collisionCount30d: 24,
    severityIndex: 79,
    primaryCause: "Sudden Braking / Rear-end",
    peakHours: "17:00 - 19:00",
    fatalAccidents: 0,
    pedestrianInvolved: false,
    riskFactor: "Major multi-lane arterial intersection near museum campus and park access"
  },
  {
    id: "ACC-09",
    intersection: "Grand Ave & Orleans St",
    lat: 41.8914,
    lng: -87.6376,
    sectorId: "SEC-02",
    collisionCount30d: 16,
    severityIndex: 68,
    primaryCause: "Illegal Left Turns",
    peakHours: "18:00 - 20:00",
    fatalAccidents: 0,
    pedestrianInvolved: false,
    riskFactor: "Off-ramp junction with complex signal phasing"
  },
  {
    id: "ACC-10",
    intersection: "Fulton St & Morgan St",
    lat: 41.8868,
    lng: -87.6521,
    sectorId: "SEC-03",
    collisionCount30d: 12,
    severityIndex: 54,
    primaryCause: "Stop Sign Non-Compliance",
    peakHours: "12:00 - 14:00",
    fatalAccidents: 0,
    pedestrianInvolved: true,
    riskFactor: "Cobblestone street transition with rideshare vehicle double-parking"
  }
];

const PATROL_UNITS = [
  {
    id: "UNIT-101",
    callsign: "Alpha-101",
    type: "Cruiser SUV",
    officers: "Off. R. Miller (Badge #4812) / Off. S. Gomez (Badge #5103)",
    status: "ON PATROL",
    assignedSector: "SEC-01",
    lat: 41.8812,
    lng: -87.6335,
    heading: 90,
    speed: 18,
    fuel: 82,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 92,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8812, -87.6335],
      [41.8850, -87.6320],
      [41.8852, -87.6275],
      [41.8790, -87.6272],
      [41.8790, -87.6335]
    ]
  },
  {
    id: "UNIT-102",
    callsign: "Bravo-202",
    type: "Cruiser SUV",
    officers: "Sgt. K. Vance (Badge #3120) / Off. M. Chen (Badge #6219)",
    status: "DISPATCHED",
    assignedSector: "SEC-02",
    lat: 41.8920,
    lng: -87.6310,
    heading: 320,
    speed: 34,
    fuel: 68,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 88,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8920, -87.6310],
      [41.8945, -87.6330],
      [41.8960, -87.6360],
      [41.8910, -87.6350]
    ]
  },
  {
    id: "UNIT-103",
    callsign: "Intercept-301",
    type: "Interceptor Sedan",
    officers: "Off. D. Jackson (Badge #4491)",
    status: "AVAILABLE",
    assignedSector: "SEC-01",
    lat: 41.8840,
    lng: -87.6280,
    heading: 180,
    speed: 0,
    fuel: 95,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 94,
    icon: "shield",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8840, -87.6280],
      [41.8860, -87.6280],
      [41.8860, -87.6350],
      [41.8800, -87.6350]
    ]
  },
  {
    id: "UNIT-104",
    callsign: "Traffic-401",
    type: "Motorcycle",
    officers: "Off. T. O'Connor (Badge #5821)",
    status: "ON PATROL",
    assignedSector: "SEC-02",
    lat: 41.8895,
    lng: -87.6265,
    heading: 45,
    speed: 25,
    fuel: 74,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 79,
    icon: "motorcycle",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8895, -87.6265],
      [41.8930, -87.6260],
      [41.8950, -87.6290],
      [41.8900, -87.6300]
    ]
  },
  {
    id: "UNIT-105",
    callsign: "K9-Tactical-1",
    type: "K9 Tactical Unit",
    officers: "Off. L. Bradley (Badge #3904) / K9 'Buster'",
    status: "ON PATROL",
    assignedSector: "SEC-03",
    lat: 41.8835,
    lng: -87.6450,
    heading: 270,
    speed: 15,
    fuel: 85,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 91,
    icon: "dog",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8835, -87.6450],
      [41.8860, -87.6490],
      [41.8830, -87.6530],
      [41.8810, -87.6470]
    ]
  },
  {
    id: "UNIT-106",
    callsign: "Charlie-203",
    type: "Cruiser SUV",
    officers: "Off. E. Rodriguez (Badge #6014) / Off. J. Patel (Badge #6388)",
    status: "ON PATROL",
    assignedSector: "SEC-03",
    lat: 41.8872,
    lng: -87.6510,
    heading: 110,
    speed: 20,
    fuel: 61,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 84,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8872, -87.6510],
      [41.8885, -87.6440],
      [41.8820, -87.6440],
      [41.8825, -87.6520]
    ]
  },
  {
    id: "UNIT-107",
    callsign: "Echo-501",
    type: "Foot Patrol",
    officers: "Off. H. Nguyen (Badge #5339) / Off. B. Larson (Badge #5912)",
    status: "ON PATROL",
    assignedSector: "SEC-05",
    lat: 41.8965,
    lng: -87.6235,
    heading: 0,
    speed: 4,
    fuel: 100,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 95,
    icon: "footsteps",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8965, -87.6235],
      [41.8990, -87.6235],
      [41.8990, -87.6200],
      [41.8950, -87.6205]
    ]
  },
  {
    id: "UNIT-108",
    callsign: "Echo-502",
    type: "Cruiser SUV",
    officers: "Off. G. Kovacs (Badge #4701)",
    status: "AVAILABLE",
    assignedSector: "SEC-05",
    lat: 41.8910,
    lng: -87.6190,
    heading: 190,
    speed: 0,
    fuel: 78,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 87,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8910, -87.6190],
      [41.8940, -87.6185],
      [41.8970, -87.6210],
      [41.8920, -87.6225]
    ]
  },
  {
    id: "UNIT-109",
    callsign: "Foxtrot-601",
    type: "Cruiser SUV",
    officers: "Off. N. Washington (Badge #5562)",
    status: "ON PATROL",
    assignedSector: "SEC-06",
    lat: 41.9040,
    lng: -87.6360,
    heading: 135,
    speed: 22,
    fuel: 89,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 76,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.9040, -87.6360],
      [41.9060, -87.6310],
      [41.9020, -87.6310],
      [41.9015, -87.6380]
    ]
  },
  {
    id: "UNIT-110",
    callsign: "Delta-402",
    type: "Cruiser SUV",
    officers: "Off. P. Morales (Badge #4928) / Off. K. Burke (Badge #5633)",
    status: "EN ROUTE",
    assignedSector: "SEC-04",
    lat: 41.8745,
    lng: -87.6315,
    heading: 160,
    speed: 30,
    fuel: 54,
    shift: "Night Shift (18:00 - 06:00)",
    coverageScore: 68,
    icon: "car",
    currentWaypointIndex: 0,
    waypoints: [
      [41.8745, -87.6315],
      [41.8710, -87.6290],
      [41.8670, -87.6270],
      [41.8690, -87.6340]
    ]
  }
];

const BLIND_SPOTS_DATA = [
  {
    id: "BLIND-01",
    sectorId: "SEC-04",
    sectorName: "South Transit & Waterfront Concourse",
    title: "South State & Roosevelt Transit Zone",
    lat: 41.8685,
    lng: -87.6270,
    radius: 420,
    riskScore: 84,
    severity: "CRITICAL",
    timeUncoveredMins: 95,
    lastPatrolledBy: "UNIT-110 (1h 35m ago)",
    reason: "Unit 110 diverted to high-priority hospital escort; station crowd surge post-train arrival.",
    suggestedAction: "Re-route Unit-103 (Intercept-301) immediately for 30-minute high-visibility deterrence.",
    nearestUnitId: "UNIT-103",
    distanceKm: 1.4
  },
  {
    id: "BLIND-02",
    sectorId: "SEC-02",
    sectorName: "River North Entertainment Strip",
    title: "Kingsbury & Hubbard Warehouse Fringe",
    lat: 41.8895,
    lng: -87.6410,
    radius: 350,
    riskScore: 78,
    severity: "HIGH",
    timeUncoveredMins: 72,
    lastPatrolledBy: "UNIT-104 (1h 12m ago)",
    reason: "Patrols concentrated on eastern nightclub strip; dark parking lots and delivery docks unmonitored.",
    suggestedAction: "Task Unit-105 (K9-Tactical-1) to execute alley sweep and parking structure check.",
    nearestUnitId: "UNIT-105",
    distanceKm: 0.8
  },
  {
    id: "BLIND-03",
    sectorId: "SEC-03",
    sectorName: "West Loop & Fulton Market",
    title: "Ogden Corridor Logistics Strip",
    lat: 41.8890,
    lng: -87.6565,
    radius: 400,
    riskScore: 69,
    severity: "MEDIUM",
    timeUncoveredMins: 64,
    lastPatrolledBy: "UNIT-106 (1h 04m ago)",
    reason: "Shift boundary gap between West Loop and Industrial District.",
    suggestedAction: "Direct Unit-106 on outbound return loop along Fulton & Ogden.",
    nearestUnitId: "UNIT-106",
    distanceKm: 0.9
  },
  {
    id: "BLIND-04",
    sectorId: "SEC-05",
    sectorName: "Magnificent Mile & Streeterville",
    title: "Fairbanks & Superior Medical Alleyway",
    lat: 41.8958,
    lng: -87.6185,
    radius: 280,
    riskScore: 66,
    severity: "MEDIUM",
    timeUncoveredMins: 58,
    lastPatrolledBy: "UNIT-108 (58m ago)",
    reason: "Heavy ambulance staging blocking standard vehicle drive-through.",
    suggestedAction: "Deploy Unit-107 (Foot Patrol) for secondary perimeter check.",
    nearestUnitId: "UNIT-107",
    distanceKm: 0.4
  }
];

const CRIME_INCIDENTS = [
  {
    id: "CR-2026-8901",
    code: "10-31",
    title: "Armed Robbery in Progress",
    category: "Violent Crime",
    type: "Armed Robbery",
    severity: "CRITICAL",
    sectorId: "SEC-02",
    sectorName: "River North",
    location: "430 N Clark St",
    lat: 41.8902,
    lng: -87.6312,
    timestamp: "12 mins ago",
    timeHoursAgo: 0.2,
    shift: "Night",
    status: "Active",
    officerResponding: "UNIT-102 (Bravo-202)",
    details: "Victim approached by two suspects displaying handgun. Cash and phone taken. Suspects fled westbound on Hubbard."
  },
  {
    id: "CR-2026-8902",
    code: "10-50",
    title: "Major Vehicle Collision with Injury",
    category: "Traffic / Accident",
    type: "Vehicle Collision",
    severity: "CRITICAL",
    sectorId: "SEC-01",
    sectorName: "Downtown Financial",
    location: "Michigan Ave & Wacker Dr",
    lat: 41.8885,
    lng: -87.6246,
    timestamp: "24 mins ago",
    timeHoursAgo: 0.4,
    shift: "Night",
    status: "Investigating",
    officerResponding: "UNIT-101 & EMS-4",
    details: "Two-vehicle collision blocking two northbound lanes. Airbag deployment. Suspected reckless lane change."
  },
  {
    id: "CR-2026-8903",
    code: "10-15",
    title: "Commercial Burglary - Jewelry Boutique",
    category: "Property Crime",
    type: "Burglary",
    severity: "HIGH",
    sectorId: "SEC-05",
    sectorName: "Magnificent Mile",
    location: "710 N Michigan Ave",
    lat: 41.8958,
    lng: -87.6243,
    timestamp: "45 mins ago",
    timeHoursAgo: 0.75,
    shift: "Night",
    status: "Investigating",
    officerResponding: "UNIT-107 & UNIT-108",
    details: "Glass shatter sensor triggered. Rear display cases forced. Perimeter secured, forensic unit en route."
  },
  {
    id: "CR-2026-8904",
    code: "10-55",
    title: "DUI Driving / Erratic Swerving",
    category: "Traffic / Accident",
    type: "DUI",
    severity: "HIGH",
    sectorId: "SEC-02",
    sectorName: "River North",
    location: "Ontario St & LaSalle Blvd",
    lat: 41.8931,
    lng: -87.6328,
    timestamp: "1h 10m ago",
    timeHoursAgo: 1.16,
    shift: "Night",
    status: "Cleared",
    officerResponding: "UNIT-104 (Traffic-401)",
    details: "Silver sedan observed running red light and striking curb. Driver detained for field sobriety test."
  },
  {
    id: "CR-2026-8905",
    code: "10-23",
    title: "Aggravated Assault / Bar Brawl",
    category: "Violent Crime",
    type: "Assault",
    severity: "HIGH",
    sectorId: "SEC-02",
    sectorName: "River North",
    location: "155 W Kinzie St",
    lat: 41.8894,
    lng: -87.6331,
    timestamp: "1h 35m ago",
    timeHoursAgo: 1.58,
    shift: "Night",
    status: "Cleared",
    officerResponding: "UNIT-102 (Bravo-202)",
    details: "Disturbance outside lounge involving multiple patrons. One victim treated for facial lacerations."
  },
  {
    id: "CR-2026-8906",
    code: "10-29",
    title: "Grand Theft Auto / Luxury SUV",
    category: "Property Crime",
    type: "Motor Vehicle Theft",
    severity: "HIGH",
    sectorId: "SEC-03",
    sectorName: "West Loop",
    location: "840 W Randolph St",
    lat: 41.8845,
    lng: -87.6491,
    timestamp: "2h 05m ago",
    timeHoursAgo: 2.08,
    shift: "Night",
    status: "Active",
    officerResponding: "UNIT-106 (Charlie-203)",
    details: "Keyless relay theft of 2024 Cadillac Escalade from valet stand staging line. LPR cameras tracking."
  },
  {
    id: "CR-2026-8907",
    code: "10-44",
    title: "Transit Pickpocketing Ring",
    category: "Property Crime",
    type: "Larceny / Theft",
    severity: "MEDIUM",
    sectorId: "SEC-04",
    sectorName: "South Transit Hub",
    location: "State & Jackson Subway Mezzanine",
    lat: 41.8781,
    lng: -87.6276,
    timestamp: "2h 40m ago",
    timeHoursAgo: 2.66,
    shift: "Evening",
    status: "Active",
    officerResponding: "Transit Special Unit",
    details: "Three victims reported stolen mobile phones and wallets during peak transfer crowding."
  },
  {
    id: "CR-2026-8908",
    code: "10-67",
    title: "Suspected Narcotics Distribution",
    category: "Narcotics",
    type: "Narcotics",
    severity: "MEDIUM",
    sectorId: "SEC-04",
    sectorName: "South Transit Hub",
    location: "Roosevelt Rd & Wabash Ave",
    lat: 41.8678,
    lng: -87.6260,
    timestamp: "3h 15m ago",
    timeHoursAgo: 3.25,
    shift: "Evening",
    status: "Active",
    officerResponding: "Tactical Squad Alpha",
    details: "Surveillance footage captured hand-to-hand transactions under CTA elevated walkway."
  },
  {
    id: "CR-2026-8909",
    code: "10-52",
    title: "Hit & Run / Bicycle Courier Struck",
    category: "Traffic / Accident",
    type: "Hit & Run",
    severity: "CRITICAL",
    sectorId: "SEC-01",
    sectorName: "Downtown Financial",
    location: "Dearborn St & Adams St",
    lat: 41.8794,
    lng: -87.6295,
    timestamp: "3h 50m ago",
    timeHoursAgo: 3.83,
    shift: "Evening",
    status: "Investigating",
    officerResponding: "UNIT-103 & Major Crash Unit",
    details: "Bicycle courier struck in protected bike lane by dark sedan making unauthorized right turn. Suspect fled south."
  },
  {
    id: "CR-2026-8910",
    code: "10-41",
    title: "Residential Garage Break-in",
    category: "Property Crime",
    type: "Burglary",
    severity: "MEDIUM",
    sectorId: "SEC-06",
    sectorName: "Near North Arts",
    location: "920 N LaSalle St",
    lat: 41.9002,
    lng: -87.6325,
    timestamp: "4h 20m ago",
    timeHoursAgo: 4.33,
    shift: "Evening",
    status: "Cleared",
    officerResponding: "UNIT-109 (Foxtrot-601)",
    details: "Multiple high-end bicycles and power tools taken from secure residential underground garage."
  },
  {
    id: "CR-2026-8911",
    code: "10-21",
    title: "Vandalism & Storefront Tagging",
    category: "Public Order",
    type: "Vandalism",
    severity: "LOW",
    sectorId: "SEC-03",
    sectorName: "West Loop",
    location: "1020 W Fulton Market",
    lat: 41.8866,
    lng: -87.6534,
    timestamp: "5h 10m ago",
    timeHoursAgo: 5.16,
    shift: "Afternoon",
    status: "Cleared",
    officerResponding: "UNIT-105 (K9-Tactical-1)",
    details: "Graffiti painted across exterior brick wall of commercial art gallery."
  },
  {
    id: "CR-2026-8912",
    code: "10-33",
    title: "Shoplifting / Organized Retail Theft",
    category: "Property Crime",
    type: "Larceny / Theft",
    severity: "MEDIUM",
    sectorId: "SEC-05",
    sectorName: "Magnificent Mile",
    location: "830 N Michigan Ave",
    lat: 41.8980,
    lng: -87.6241,
    timestamp: "5h 45m ago",
    timeHoursAgo: 5.75,
    shift: "Afternoon",
    status: "Cleared",
    officerResponding: "UNIT-107 (Echo-501)",
    details: "Three individuals concealed designer apparel exceeding $4,500 value in booster bags."
  },
  {
    id: "CR-2026-8913",
    code: "10-50",
    title: "Three-Car Pileup on Expressway Ramp",
    category: "Traffic / Accident",
    type: "Vehicle Collision",
    severity: "HIGH",
    sectorId: "SEC-04",
    sectorName: "South Transit Hub",
    location: "Congress Pkwy & Financial Pl",
    lat: 41.8752,
    lng: -87.6322,
    timestamp: "6h 30m ago",
    timeHoursAgo: 6.5,
    shift: "Afternoon",
    status: "Cleared",
    officerResponding: "UNIT-110 & Highway Patrol",
    details: "Sudden slowdown triggered chain-reaction rear-end collision. Extensive debris cleared."
  },
  {
    id: "CR-2026-8914",
    code: "10-31",
    title: "Street Robbery at Gunpoint",
    category: "Violent Crime",
    type: "Armed Robbery",
    severity: "CRITICAL",
    sectorId: "SEC-04",
    sectorName: "South Transit Hub",
    location: "Michigan Ave & 11th St",
    lat: 41.8690,
    lng: -87.6245,
    timestamp: "7h 15m ago",
    timeHoursAgo: 7.25,
    shift: "Afternoon",
    status: "Active",
    officerResponding: "UNIT-110 (Delta-402)",
    details: "Victim walking towards train station was confronted by suspect demanding backpack."
  },
  {
    id: "CR-2026-8915",
    code: "10-16",
    title: "Domestic Disturbance Call",
    category: "Violent Crime",
    type: "Domestic Disturbance",
    severity: "HIGH",
    sectorId: "SEC-06",
    sectorName: "Near North Arts",
    location: "1120 N Dearborn St",
    lat: 41.9035,
    lng: -87.6300,
    timestamp: "8h 00m ago",
    timeHoursAgo: 8.0,
    shift: "Morning",
    status: "Cleared",
    officerResponding: "UNIT-109 (Foxtrot-601)",
    details: "Verbal dispute escalating inside condominium unit. Parties separated safely."
  },
  {
    id: "CR-2026-8916",
    code: "10-25",
    title: "Car Prowling / Multiple Vehicles Broken Into",
    category: "Property Crime",
    type: "Motor Vehicle Theft",
    severity: "MEDIUM",
    sectorId: "SEC-03",
    sectorName: "West Loop",
    location: "1100 W Washington Blvd",
    lat: 41.8832,
    lng: -87.6548,
    timestamp: "9h 20m ago",
    timeHoursAgo: 9.33,
    shift: "Morning",
    status: "Active",
    officerResponding: "UNIT-106 (Charlie-203)",
    details: "Five vehicles had rear side windows smashed in paid surface parking lot."
  },
  {
    id: "CR-2026-8917",
    code: "10-50",
    title: "Pedestrian Struck by Rideshare",
    category: "Traffic / Accident",
    type: "Vehicle Collision",
    severity: "HIGH",
    sectorId: "SEC-02",
    sectorName: "River North",
    location: "Ontario St & Clark St",
    lat: 41.8932,
    lng: -87.6315,
    timestamp: "10h 45m ago",
    timeHoursAgo: 10.75,
    shift: "Morning",
    status: "Investigating",
    officerResponding: "UNIT-104 & Traffic Division",
    details: "Pedestrian crossing with walk signal struck by left-turning sedan. Non-life-threatening injury."
  },
  {
    id: "CR-2026-8918",
    code: "10-44",
    title: "ATM Skimming Device Discovered",
    category: "Property Crime",
    type: "Fraud",
    severity: "LOW",
    sectorId: "SEC-01",
    sectorName: "Downtown Financial",
    location: "200 S LaSalle St",
    lat: 41.8798,
    lng: -87.6328,
    timestamp: "12h 10m ago",
    timeHoursAgo: 12.16,
    shift: "Morning",
    status: "Cleared",
    officerResponding: "UNIT-101 (Alpha-101)",
    details: "Bank branch technician found magnetic skimmer and pinhole camera mounted to vestibule ATM."
  },
  {
    id: "CR-2026-8919",
    code: "10-31",
    title: "Attempted Strong-Arm Robbery",
    category: "Violent Crime",
    type: "Robbery",
    severity: "HIGH",
    sectorId: "SEC-02",
    sectorName: "River North",
    location: "Hubbard St & Wells St",
    lat: 41.8898,
    lng: -87.6341,
    timestamp: "14h 00m ago",
    timeHoursAgo: 14.0,
    shift: "Night",
    status: "Cleared",
    officerResponding: "UNIT-102 (Bravo-202)",
    details: "Victim resisted suspect attempt to grab shoulder bag. Suspect fled on electric scooter."
  },
  {
    id: "CR-2026-8920",
    code: "10-67",
    title: "Open-Air Drug Transaction / Weapon Seized",
    category: "Narcotics",
    type: "Narcotics",
    severity: "HIGH",
    sectorId: "SEC-04",
    sectorName: "South Transit Hub",
    location: "State St & Balbo Ave",
    lat: 41.8732,
    lng: -87.6276,
    timestamp: "16h 30m ago",
    timeHoursAgo: 16.5,
    shift: "Evening",
    status: "Cleared",
    officerResponding: "UNIT-110 & Gang Unit",
    details: "Undercover officers observed narcotics sale. Suspect fled into alley; ghost handgun recovered."
  },
  {
    id: "CR-2026-8921",
    code: "10-50",
    title: "Delivery Van Rollover Incident",
    category: "Traffic / Accident",
    type: "Vehicle Collision",
    severity: "HIGH",
    sectorId: "SEC-03",
    sectorName: "West Loop",
    location: "Halsted St & Randolph St",
    lat: 41.8845,
    lng: -87.6475,
    timestamp: "19h 15m ago",
    timeHoursAgo: 19.25,
    shift: "Afternoon",
    status: "Cleared",
    officerResponding: "UNIT-105 & Fire Rescue",
    details: "Delivery van struck traffic island curb at high speed, tipping onto passenger side. Fuel spill contained."
  },
  {
    id: "CR-2026-8922",
    code: "10-21",
    title: "Luxury Storefront Window Shattered",
    category: "Public Order",
    type: "Vandalism",
    severity: "LOW",
    sectorId: "SEC-05",
    sectorName: "Magnificent Mile",
    location: "650 N Michigan Ave",
    lat: 41.8942,
    lng: -87.6245,
    timestamp: "21h 00m ago",
    timeHoursAgo: 21.0,
    shift: "Morning",
    status: "Cleared",
    officerResponding: "UNIT-108 (Echo-502)",
    details: "Heavy metal object thrown through display plate glass; no merchandise accessed."
  },
  {
    id: "CR-2026-8923",
    code: "10-15",
    title: "After-Hours Office Safe Burglary",
    category: "Property Crime",
    type: "Burglary",
    severity: "HIGH",
    sectorId: "SEC-01",
    sectorName: "Downtown Financial",
    location: "111 W Monroe St",
    lat: 41.8808,
    lng: -87.6315,
    timestamp: "23h 30m ago",
    timeHoursAgo: 23.5,
    shift: "Night",
    status: "Investigating",
    officerResponding: "UNIT-101 (Alpha-101)",
    details: "Perimeter door bypassed using cloned RFID keycard. Financial safe forced with torch tool."
  }
];

// Temporal Crime Matrix: 7 Days (Mon to Sun) x 24 Hours (00:00 to 23:00)
// Value represents relative risk density index (0 to 100)
const TIME_DAY_HEATMAP_MATRIX = {
  days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  hours: [
    "00:00", "01:00", "02:00", "03:00", "04:00", "05:00",
    "06:00", "07:00", "08:00", "09:00", "10:00", "11:00",
    "12:00", "13:00", "14:00", "15:00", "16:00", "17:00",
    "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"
  ],
  // Grid values [dayIndex][hourIndex]
  matrix: [
    // Mon: rush hours + modest evening
    [32, 24, 18, 12, 10, 15, 38, 72, 81, 65, 45, 52, 60, 54, 58, 69, 78, 85, 76, 62, 55, 48, 40, 36],
    // Tue: steady commercial + commute accidents
    [28, 20, 15, 11, 12, 16, 42, 75, 83, 62, 48, 55, 64, 58, 62, 71, 80, 88, 74, 60, 52, 45, 38, 32],
    // Wed: mid-week peak
    [30, 22, 16, 12, 14, 18, 45, 78, 85, 68, 52, 59, 68, 61, 65, 75, 82, 90, 78, 65, 58, 52, 44, 38],
    // Thu: early weekend warmup, late night bars
    [35, 28, 20, 15, 14, 20, 44, 76, 84, 66, 54, 62, 70, 64, 68, 78, 84, 91, 82, 72, 68, 64, 58, 52],
    // Fri: evening surge, nightlife, violent crime peak
    [48, 38, 30, 22, 18, 22, 46, 74, 82, 68, 60, 72, 78, 74, 80, 88, 92, 95, 92, 88, 86, 90, 94, 98],
    // Sat: late night peak, retail afternoon, major entertainment incidents
    [96, 94, 88, 65, 42, 26, 22, 28, 35, 48, 65, 75, 82, 85, 86, 88, 86, 89, 90, 92, 95, 97, 98, 99],
    // Sun: late night cooldown, family daytime, evening transit pickup
    [92, 84, 68, 48, 30, 18, 15, 20, 26, 36, 48, 58, 62, 60, 58, 62, 68, 72, 75, 70, 62, 54, 46, 38]
  ]
};

// AI Patrol Recommendations Templates
const PATROL_RECOMMENDATIONS = [
  {
    id: "REC-01",
    sectorId: "SEC-02",
    sectorName: "River North & Entertainment Strip",
    priority: "CRITICAL",
    riskScore: 86,
    targetWindow: "21:00 - 03:30 (Peak Bar Egress)",
    assignedUnit: "UNIT-102 (Bravo-202) & UNIT-104",
    title: "High-Visibility Nightlife Corridor Intercept",
    strategy: "Dual-unit alternating presence along Hubbard and Clark corridors. Deploy pedestrian safety checkpoints to curb DUI and assault spikes.",
    projectedRiskReduction: "-28% Violent Incidents",
    waypoints: [
      { name: "Ontario & Clark (DUI Hotspot ACC-02)", durationMins: 20, type: "Static Deterrence" },
      { name: "Hubbard St Club Row", durationMins: 25, type: "Slow Foot/Vehicle Sweep" },
      { name: "Kingsbury Warehouse Fringe (Blind Spot BLIND-02)", durationMins: 15, type: "Dark Alley Searchlight Check" }
    ]
  },
  {
    id: "REC-02",
    sectorId: "SEC-04",
    sectorName: "South Transit & Waterfront Concourse",
    priority: "CRITICAL",
    riskScore: 78,
    targetWindow: "Immediate (Coverage Deficit)",
    assignedUnit: "UNIT-103 (Intercept-301)",
    title: "Transit Plaza Rapid Re-Establishment Sweep",
    strategy: "Sector 4 has been uncovered for 95+ mins due to prior hospital diversion. Redeploy Unit-103 from financial standby to Roosevelt & State station concourses.",
    projectedRiskReduction: "-34% Pickpocketing & Robbery",
    waypoints: [
      { name: "State & Jackson Subway Mezzanine", durationMins: 25, type: "Foot Patrol Presence" },
      { name: "Roosevelt & Wabash Transit Walkway", durationMins: 20, type: "Narcotics Deterrence" },
      { name: "State & Ida B. Wells Expressway Crossing", durationMins: 15, type: "Traffic Calming" }
    ]
  },
  {
    id: "REC-03",
    sectorId: "SEC-01",
    sectorName: "Downtown Financial Core",
    priority: "HIGH",
    riskScore: 71,
    targetWindow: "07:30 - 09:30 & 16:30 - 19:00",
    assignedUnit: "UNIT-101 (Alpha-101)",
    title: "Commuter Corridor & Multi-Level Bridge Patrol",
    strategy: "Maintain high-profile beacon presence at Wacker & Michigan bridge to suppress both aggressive driving accidents and courier bike conflicts.",
    projectedRiskReduction: "-22% Traffic Collisions",
    waypoints: [
      { name: "Michigan Ave & Wacker Dr (Hotspot ACC-01)", durationMins: 30, type: "Traffic Enforcement" },
      { name: "Dearborn & Adams Cycle Track", durationMins: 20, type: "Bike Lane Clearance" },
      { name: "LaSalle Financial Arcade", durationMins: 15, type: "Commercial Foot Check" }
    ]
  },
  {
    id: "REC-04",
    sectorId: "SEC-03",
    sectorName: "West Loop & Fulton Market",
    priority: "HIGH",
    riskScore: 65,
    targetWindow: "19:00 - 01:00",
    assignedUnit: "UNIT-105 (K9-Tactical-1)",
    title: "Valet Staging & Commercial Garage K9 Sweep",
    strategy: "Targeted K9 sweep through restaurant row surface lots to counter recent string of keyless relay luxury vehicle thefts.",
    projectedRiskReduction: "-40% Vehicle Prowling",
    waypoints: [
      { name: "Randolph Valet Parking Staging Lots", durationMins: 25, type: "K9 Vehicle Perimeter Sweep" },
      { name: "Fulton Market Cobblestone Corridor", durationMins: 20, type: "Visibility Deterrence" },
      { name: "Ogden Logistics Corridor (BLIND-03)", durationMins: 15, type: "Alley & Dock Inspection" }
    ]
  }
];
